# Main configuration for RL Web Agent
# @package _global_
#
# Single configuration file with all settings.
# Override any setting from the command line:
#   python -m rl_web_agent.main environment.browser.headless=true environment.proxy.enabled=false

# ============================================================================
# ENVIRONMENT CONFIGURATION
# ============================================================================
# Web environment including browser, proxy, and script paths
environment:
  # Site configurations - mapping of site names to their hostnames
  # These hostnames will be rewritten to actual IP addresses by the proxy
  sites:
    shopping: "metis.lti.cs.cmu.edu:7770"
    shopping_admin: "ec2-3-131-244-37.us-east-2.compute.amazonaws.com:7780"
    reddit: "ec2-3-131-244-37.us-east-2.compute.amazonaws.com:9999"
    gitlab: "ec2-3-131-244-37.us-east-2.compute.amazonaws.com:8023"
    map: "ec2-3-131-244-37.us-east-2.compute.amazonaws.com:3000"
    wikipedia: "ec2-3-131-244-37.us-east-2.compute.amazonaws.com:8888"

  init_script_path: "rl_web_agent/javascript/initscript.js"   # Path to JavaScript init script
  parser_script_path: "rl_web_agent/javascript/parser.js"     # Path to JavaScript parser script

  # Proxy configuration
  proxy:
    server: "http://localhost:8080"    # Proxy server URL (must be running)
    enabled: true                      # Enable proxy routing (set false to bypass)

  # Browser configuration
  # Maps directly to Playwright's launch and context options
  # Add any Playwright option by following their API structure:
  # https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch
  # https://playwright.dev/python/docs/api/class-browser#browser-new-context
  browser:
    # Launch options
    launch_options:
      headless: false                  # Show browser window (set true for CI/automation)
      args:                           # Performance optimization args
        - "--disable-autofill-keyboard-accessory-view"
        - "--disable-autofill-profile-update"
        - "--disable-autofill"
        - "--disable-extensions"
        - "--disable-background-networking"
        - "--safebrowsing-disable-auto-update"
        - "--disable-component-update"
        - "--disable-default-apps"
        - "--no-first-run"
        - "--no-default-browser-check"
        - "--metrics-recording-only"
        - "--disable-sync"
        - "--disable-translate"
        - "--disable-features=NetworkService,NetworkServiceInProcess"
        - "--disable-client-side-phishing-detection"
        - "--disable-domain-reliability"
        - "--disable-crash-reporter"

    # Context options
    context_options:
      viewport:
        width: 1920                    # Browser viewport width in pixels
        height: 1080                   # Browser viewport height in pixels
      user_agent: null                 # User agent string to use
      extra_http_headers: null         # Will be set for host rewrites if needed

    # Custom behavior options
    block_images: true                 # Block loading of images to speed up browsing

    # Browser cache and data directories
    cache_dir: "./browser_cache"       # Persistent network cache directory
    user_data_dir: "./browser_session" # User data directory (cookies, session data)

    # Timeout configurations (in milliseconds)
    timeouts:
      locator_action: 5000        # Timeout for locator actions (click, type, etc.)
      page_load_domcontent: 10000 # Timeout for DOM content loaded
      page_load_networkidle: 30000 # Timeout for network idle (longer for full page loads)
      element_wait: 5000          # Timeout for waiting for specific elements

# ============================================================================
# GENERAL SETTINGS
# ============================================================================
debug: false           # Enable debug logging and detailed output
log_level: INFO        # Logging level: DEBUG, INFO, WARNING, ERROR

# ============================================================================
# HYDRA SETTINGS
# ============================================================================
# Controls output directory and job behavior
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}  # Timestamped output directory
  job:
    chdir: false       # Don't change working directory during execution
